# Week 7 Project

## Jhader Aguad

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

Here is my content!

```{r}
library(rvest)
library(lubridate)
page <- "http://en.wikipedia.org/wiki/List_of_nuclear_reactors"
table_nodes <- page %>%
  read_html() %>%
  html_nodes("table")
table_list <-
  html_table(table_nodes[1:30], fill = TRUE)
```
##Create Japan Table
```{r}
japan_table <- table_list[[24]] 
```
##Remove first Row
```{r}
ncol(japan_table)
nrow(japan_table)
new_names <- c("Name", "Reactor", "Type", "Model", "Status", "CapacityNet", "CapacityGross", "ConstructionDate", "CommercialDate", "Closure")
names(japan_table) <- new_names
japan_table <- japan_table[-1, ]
nrow(japan_table)
```
##Lubridate
```{r}
japan_table <- japan_table %>%
  mutate(construction =
  lubridate::dmy(ConstructionDate))

japan_table <- japan_table %>%
  mutate(commercial =
  lubridate::dmy(CommercialDate))

japan_table <- japan_table %>%
  mutate(closure =
  lubridate::dmy(Closure))
```

4. A quick visualization
```{r}
ggplot(japan_table,aes(x=construction, y=Name)) + geom_segment(aes(x=construction, y=Name,xend=commercial,yend=Name,color=Reactor))
```

